### ISSUE TITLE
Google Cloud Translate collides with Firebase FireStore, and makes an error.

### ISSUE THREAD

**Issue by tuxxon** [googleapis/java-translate#300]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/java-translate/issues
  - Check for answers on StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform

If you are still having issues, please include as much information as possible:

#### Environment details
1. The specified api: API : com.google.firebase:firebase-firestore:21.7.1
2. OS type and version:   AndroidEmulator = api level 28
3. Java version:   Java SDK 1.8
4. translation version(s): 1.95.2

#### Steps to reproduce

1.  Google Cloud Translate collides with Firestore.
 * collision 1
```
Duplicate class com.google.api.Advice found in modules jetified-proto-google-common-protos-1.18.0.jar (com.google.api.grpc:proto-google-common-protos:1.18.0) and jetified-protolite-well-known-types-17.1.0-runtime.jar (com.google.firebase:protolite-well-known-types:17.1.0)
```
* collision 2 
```
Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-java-3.12.4.jar (com.google.protobuf:protobuf-java:3.12.4) and jetified-protobuf-javalite-3.12.0.jar (com.google.protobuf:protobuf-javalite:3.12.0)
```

  2.  Fatal errors occur on running.
  To remove collisions, if using the followings
```
  implementation.exclude(group: 'com.google.firebase', module: 'protolite-well-known-types')
  implementation.exclude(group: 'com.google.protobuf', module: 'protobuf-javalite')
```

I got the following errors
```
2020-10-09 11:28:48.853 23328-23328/com.touchizen.deepshadowing E/ACRA: ACRA caught a RuntimeException for com.touchizen.deepshadowing
    java.lang.RuntimeException: Internal error in Cloud Firestore (21.7.1).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:534)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.VerifyError: Verifier rejected class com.google.firestore.v1.WriteResponse: void com.google.firestore.v1.WriteResponse.mergeCommitTime(com.google.protobuf.Timestamp) failed to verify: void com.google.firestore.v1.WriteResponse.mergeCommitTime(com.google.protobuf.Timestamp): [0x13] register v3 has type Precise Reference: com.google.protobuf.Timestamp but expected Reference: com.google.protobuf.GeneratedMessageLite (declaration of 'com.google.firestore.v1.WriteResponse' appears in /data/app/com.touchizen.deepshadowing-ZoaMVJ8YiEb7uNQCDr1Bkg==/base.apk!classes3.dex)
        at com.google.firestore.v1.WriteResponse.getDefaultInstance(WriteResponse.java:898)
        at com.google.firestore.v1.FirestoreGrpc.getWriteMethod(FirestoreGrpc.java:368)
        at com.google.firebase.firestore.remote.WriteStream.<init>(WriteStream.java:74)
        at com.google.firebase.firestore.remote.Datastore.createWriteStream(Datastore.java:120)
        at com.google.firebase.firestore.remote.RemoteStore.<init>(RemoteStore.java:186)
        at com.google.firebase.firestore.core.MemoryComponentProvider.createRemoteStore(MemoryComponentProvider.java:72)
        at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:135)
        at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:249)
        at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0(FirestoreClient.java:96)
        at com.google.firebase.firestore.core.FirestoreClient$$Lambda$1.run(Unknown Source:8)
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:436)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(Unknown Source:2)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:322)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229)
        at java.lang.Thread.run(Thread.java:764)
2020-10-09 11:28:49.140 1538-1538/? E/SELinux: avc:  denied  { find } for service=meminfo pid=23521 uid=10117 scontext=u:r:untrusted_app:s0:c117,c256,c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
```

#### Code example

```java
        /**
         * Firebase: RealtimeDatabase and Firestore.
         */
        mRealtimeDatabase = FirebaseDatabase.getInstance().getReference().child(VIDEO_DETAIL_KEY);
        mFirestore = FirebaseFirestore.getInstance();
        mSubtitleDoc = mFirestore.collection("subtitles").document(getVideoId());
        mSubtitleDoc.get().addOnCompleteListener(this);

        /**
         * Cloud Translate
         */

        try {
            mTranslationServiceSettings = TranslateText.initTranslationServiceSettings(getContext());
            mTranslationClient = TranslationServiceClient.create(mTranslationServiceSettings);

            LocationName parent = LocationName.of(getResources().getString(R.string.project_id), "us-central1");
            mTranslationRequest =
                    TranslateTextRequest.newBuilder()
                            .setParent(parent.toString())
                            .setMimeType("text/plain")
                            .setSourceLanguageCode("KO")
                            .setTargetLanguageCode("EN");

        } catch (IOException e) {
            e.printStackTrace();
        }
```

#### Stack trace
```
2020-10-09 11:28:48.853 23328-23328/com.touchizen.deepshadowing E/ACRA: ACRA caught a RuntimeException for com.touchizen.deepshadowing
    java.lang.RuntimeException: Internal error in Cloud Firestore (21.7.1).
        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:534)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.VerifyError: Verifier rejected class com.google.firestore.v1.WriteResponse: void com.google.firestore.v1.WriteResponse.mergeCommitTime(com.google.protobuf.Timestamp) failed to verify: void com.google.firestore.v1.WriteResponse.mergeCommitTime(com.google.protobuf.Timestamp): [0x13] register v3 has type Precise Reference: com.google.protobuf.Timestamp but expected Reference: com.google.protobuf.GeneratedMessageLite (declaration of 'com.google.firestore.v1.WriteResponse' appears in /data/app/com.touchizen.deepshadowing-ZoaMVJ8YiEb7uNQCDr1Bkg==/base.apk!classes3.dex)
        at com.google.firestore.v1.WriteResponse.getDefaultInstance(WriteResponse.java:898)
        at com.google.firestore.v1.FirestoreGrpc.getWriteMethod(FirestoreGrpc.java:368)
        at com.google.firebase.firestore.remote.WriteStream.<init>(WriteStream.java:74)
        at com.google.firebase.firestore.remote.Datastore.createWriteStream(Datastore.java:120)
        at com.google.firebase.firestore.remote.RemoteStore.<init>(RemoteStore.java:186)
        at com.google.firebase.firestore.core.MemoryComponentProvider.createRemoteStore(MemoryComponentProvider.java:72)
        at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:135)
        at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:249)
        at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0(FirestoreClient.java:96)
        at com.google.firebase.firestore.core.FirestoreClient$$Lambda$1.run(Unknown Source:8)
        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:436)
        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(Unknown Source:2)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:322)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229)
        at java.lang.Thread.run(Thread.java:764)
2020-10-09 11:28:49.140 1538-1538/? E/SELinux: avc:  denied  { find } for service=meminfo pid=23521 uid=10117 scontext=u:r:untrusted_app:s0:c117,c256,c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
```

#### External references such as API reference guides

* https://github.com/firebase/firebase-android-sdk

#### Any additional information below
* https://github.com/firebase/firebase-android-sdk/issues/2054

Let me know how to solve this problem.

**Comment by suraj-qlogic** [comment]
@tuxxon ,Thanks for filling an issue.Here if we use ```google-cloud-translate``` gradle dependency some proto file class bytecode is not verified at runtime Here ```google-cloud-translate``` internally use ```google-api-services-translate``` for translate text using rest api.Can you try below config and please let us know it's help you?


**build.gradle(:app)**
```java
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
android {
    compileSdkVersion 29

    defaultConfig {
        applicationId "your-app-packagename"
        minSdkVersion 28
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    packagingOptions {
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
        exclude("META-INF/*.kotlin_module")
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    dependenciesInfo {
        includeInApk true
        includeInBundle true
    }
}
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.2'
    implementation 'androidx.navigation:navigation-fragment:2.3.0'
    implementation 'androidx.navigation:navigation-ui:2.3.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.google.firebase:firebase-firestore:21.7.1'
    implementation 'com.google.apis:google-api-services-translate:v2-rev20170525-1.30.10'
    implementation 'com.google.auth:google-auth-library-oauth2-http:0.22.0'
}

````
For translate client require gcp credential so put ```google-gcp-credential.json``` in resource/raw folder which is You can alternately choose to explicitly point to your service account file in code, as shown in the following example.
**Code::**
```java
 FirebaseFirestore mFirestore = FirebaseFirestore.getInstance();
// Create a new user with a first and last name
mFirestore.collection("users")
        .get()
        .addOnCompleteListener(new OnCompleteListener<QuerySnapshot>() {
            @Override
            public void onComplete(@NonNull Task<QuerySnapshot> task) {
                if (task.isSuccessful()) {
                    for (QueryDocumentSnapshot document : task.getResult()) {
                        Log.d(TAG, document.getId() + " => " + document.getData());
                    }
                } else {
                    Log.w(TAG, "Error getting documents.", task.getException());
                }
            }
        });

try {
   InputStream inputStream = resources.openRawResource(R.raw.google-gcp-credential);
   GoogleCredentials credentials = GoogleCredentials.fromStream(inputStream).createScoped(TranslateScopes.all());
   HttpRequestInitializer requestInitializer = new HttpCredentialsAdapter(credentials);
   // Create the credential
   HttpTransport transport = new NetHttpTransport();
   JsonFactory jsonFactory = new JacksonFactory();
   Translate translate = new Translate.Builder(transport, jsonFactory, requestInitializer)
           .setApplicationName("hello-test")
           .build();
   String sourceLanguage = "en";
   String targetLanguage = "ru";
   List<String> texts = new LinkedList<>();
   texts.add("Hello This is a simple text.....");
   List<TranslationsResource> translationsResourceList =
           translate
                   .translations()
                   .list(texts, targetLanguage)
                   .setSource(sourceLanguage)
                   .setKey(null)
                   .set("model", null)
                   .setFormat(null)
                   .execute()
                   .getTranslations();
   Log.d(TAG, translationsResourceList.toString());
}catch (IOException e){

}
```
**Output::**
D/ContentValues: [{"translatedText":"Привет Это простой текст ....."}]
D/ContentValues: 5XvHuWW53S69baBBHYSr => {last=Lovelace, born=1815, first=Ada}
    AB8yCH5uO8QAJZXAdFt9 => {result={isSuccess=true}}

**Comment by tuxxon** [comment]
@suraj-qlogic Thanks for responding. This issue was solved for me because I found Cloud Translation is for server, credentials.json should not be leaked out and the related code should be put to server.

Really Thanks for following this issue to the end.

Gordon Ahn.

**Comment by lizhiwei92** [comment]
> @suraj-qlogic Thanks for responding. This issue was solved for me because I found Cloud Translation is for server, credentials.json should not be leaked out and the related code should be put to server.
> 
> Really Thanks for following this issue to the end.
> 
> Gordon Ahn.

so, how to use Cloud Translation in Android is the best practice?

**Comment by tuxxon** [comment]
@lizhiwei92 I am not sure, if you know anything, let me know about that.
